"""initial schema"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
revision='001_initial';down_revision=None;branch_labels=None;depends_on=None
UUID=postgresql.UUID(as_uuid=True)
def e(name,*values): return sa.Enum(*values,name=name)
def upgrade():
 op.execute('CREATE EXTENSION IF NOT EXISTS pgcrypto')
 op.create_table('projects',sa.Column('id',UUID,primary_key=True,server_default=sa.text('gen_random_uuid()')),sa.Column('name',sa.String(255),nullable=False),sa.Column('client_name',sa.String(255),nullable=False),sa.Column('description',sa.String(1000)),sa.Column('status',e('ACTIVE','COMPLETED','ARCHIVED',name='projectstatus'),nullable=False),sa.Column('created_at',sa.DateTime(),server_default=sa.func.now()),sa.Column('updated_at',sa.DateTime(),server_default=sa.func.now()))
 op.create_table('documents',sa.Column('id',UUID,primary_key=True,server_default=sa.text('gen_random_uuid()')),sa.Column('project_id',UUID,sa.ForeignKey('projects.id',ondelete='CASCADE'),nullable=False),sa.Column('doc_type',e('TOR','RAB','ACUAN','KEPMEN','SBM',name='doctype'),nullable=False),sa.Column('file_name',sa.String(500),nullable=False),sa.Column('file_path',sa.String(1000),nullable=False),sa.Column('extracted_text',sa.Text()),sa.Column('status',e('PENDING','PROCESSING','PROCESSED','ERROR',name='docstatus'),nullable=False),sa.Column('uploaded_at',sa.DateTime(),server_default=sa.func.now()),sa.Column('processed_at',sa.DateTime()));op.create_index('ix_documents_project_id','documents',['project_id'])
 op.create_table('chunks',sa.Column('id',UUID,primary_key=True,server_default=sa.text('gen_random_uuid()')),sa.Column('document_id',UUID,sa.ForeignKey('documents.id',ondelete='CASCADE'),nullable=False),sa.Column('content',sa.Text(),nullable=False),sa.Column('chunk_index',sa.Integer(),nullable=False),sa.Column('chunk_type',e('PARAGRAF','PASAL',name='chunktype'),nullable=False),sa.Column('pasal_number',sa.String(50)),sa.Column('page_number',sa.Integer()),sa.Column('qdrant_point_id',sa.String(100)),sa.Column('collection_name',sa.String(100),nullable=False),sa.Column('metadata_json',sa.JSON()),sa.Column('created_at',sa.DateTime(),server_default=sa.func.now()));op.create_index('ix_chunks_document_id','chunks',['document_id'])
 op.create_table('checklist_items',sa.Column('id',UUID,primary_key=True,server_default=sa.text('gen_random_uuid()')),sa.Column('checklist_number',sa.Integer(),nullable=False),sa.Column('item_key',sa.String(100),nullable=False,unique=True),sa.Column('description',sa.String(500),nullable=False),sa.Column('category',sa.String(50),nullable=False),sa.Column('is_active',sa.Boolean(),nullable=False,server_default=sa.true()),sa.Column('created_at',sa.DateTime(),server_default=sa.func.now()))
 op.create_table('screening_sessions',sa.Column('id',UUID,primary_key=True,server_default=sa.text('gen_random_uuid()')),sa.Column('project_id',UUID,sa.ForeignKey('projects.id',ondelete='CASCADE'),nullable=False),sa.Column('screening_number',sa.Integer(),nullable=False),sa.Column('status',e('PENDING','RUNNING','COMPLETED','FAILED',name='screeningstatus'),nullable=False),sa.Column('started_at',sa.DateTime()),sa.Column('completed_at',sa.DateTime()),sa.Column('final_result',e('LOLOS','REVISI','TIDAK_LOLOS',name='finalresult')),sa.Column('rocan_approved',sa.Boolean()),sa.Column('rocan_approved_at',sa.DateTime()),sa.Column('created_at',sa.DateTime(),server_default=sa.func.now()));op.create_index('ix_screening_sessions_project_id','screening_sessions',['project_id'])
 for n,cols in [('format_check_results',[sa.Column('session_id',UUID,sa.ForeignKey('screening_sessions.id',ondelete='CASCADE'),nullable=False),sa.Column('document_id',UUID,sa.ForeignKey('documents.id',ondelete='CASCADE'),nullable=False),sa.Column('checklist_item_id',UUID,sa.ForeignKey('checklist_items.id'),nullable=False),sa.Column('passed',sa.Boolean(),nullable=False),sa.Column('notes',sa.Text()),sa.Column('checked_at',sa.DateTime(),server_default=sa.func.now())]),('screening_results',[sa.Column('session_id',UUID,sa.ForeignKey('screening_sessions.id',ondelete='CASCADE'),nullable=False),sa.Column('document_id',UUID,sa.ForeignKey('documents.id',ondelete='CASCADE'),nullable=False),sa.Column('stage',e('FORMAT','SUBSTANSI',name='screeningstage'),nullable=False),sa.Column('passed',sa.Boolean(),nullable=False),sa.Column('summary',sa.Text()),sa.Column('created_at',sa.DateTime(),server_default=sa.func.now())]),('llm_outputs',[sa.Column('session_id',UUID,sa.ForeignKey('screening_sessions.id',ondelete='CASCADE'),nullable=False),sa.Column('document_id',UUID,sa.ForeignKey('documents.id',ondelete='CASCADE'),nullable=False),sa.Column('checklist_item_id',UUID,sa.ForeignKey('checklist_items.id')),sa.Column('classification',e('LOLOS','TIDAK_LOLOS','PERLU_REVISI',name='llmclassification'),nullable=False),sa.Column('recommendation',sa.Text(),nullable=False),sa.Column('reason',sa.Text(),nullable=False),sa.Column('evidence_json',sa.JSON()),sa.Column('raw_prompt',sa.Text()),sa.Column('raw_response',sa.Text()),sa.Column('created_at',sa.DateTime(),server_default=sa.func.now())])]:
  op.create_table(n,sa.Column('id',UUID,primary_key=True,server_default=sa.text('gen_random_uuid()')),*cols)
  op.create_index('ix_'+n+'_session_id',n,['session_id'])
def downgrade():
 for n in ['llm_outputs','screening_results','format_check_results','screening_sessions','checklist_items','chunks','documents','projects']:op.drop_table(n)
